# HTTP Server.
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库连接配置
database:
  logger:
    path: "temp/logs/sql"
    level: "all"
    stdout: true
    ctxKeys: ["RequestId"]

  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/gf_shop?parseTime=true&loc=Local"
    debug: true
