apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-single
  labels:
    app: focus-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focus-single
  template:
    metadata:
      labels:
        app: focus-single
    spec:
      containers:
        - name : main
          image: focus-single
          imagePullPolicy: Always

