apiVersion: apps/v1
kind: Deployment
metadata:
  name: goframe-xinfeng
  labels:
    app: goframe-xinfeng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goframe-xinfeng
  template:
    metadata:
      labels:
        app: goframe-xinfeng
    spec:
      containers:
        - name : main
          image: goframe-xinfeng
          imagePullPolicy: Always

